const data = [
  {
    id: 1,
    name: "Guion sobre Periféricos e Interfaces",
    contenido: [
      "En este video voy a analizar cómo interactúan los periféricos con el procesador basándome en la arquitectura de buses moderna.",
      "Casi siempre pensamos que la velocidad de una computadora depende solo del procesador, pero los periféricos son el eslabón más vital y a la vez el más lento del sistema.",
      "La razón es física: el CPU opera en nanosegundos, mientras que los periféricos trabajan a velocidades mecánicas o humanas, medidas en milisegundos.",
      "Para evitar que el procesador pase el 99% de su tiempo esperando respuestas de dispositivos lentos, la arquitectura utiliza el PCH o Platform Controller Hub.",
      "Este componente actúa como un gestor de tráfico que recoge los datos de los periféricos, los empaqueta y se los entrega ordenados al procesador.",
      "Tomemos como ejemplo el teclado y el escáner. El teclado traduce pulsaciones en pequeños códigos binarios de escaneo mediante el protocolo HID por USB.",
      "El escáner, en cambio, maneja volúmenes masivos de datos para digitalizar imágenes y suele usar protocolos como TWAIN para la transferencia.",
      "En cuanto a la salida, el monitor es el más exigente, conectándose por HDMI o DisplayPort directamente a la gráfica mediante buses PCIe de alta velocidad.",
      "La impresora, por otro lado, utiliza lenguajes como PostScript y reporta constantemente su estado, como niveles de tinta o atascos de papel.",
      "Todo este diseño se sostiene bajo tres ideas: la jerarquía de velocidad, el mecanismo de interrupciones para no saturar al CPU, y la prevención de cuellos de botella.",
      "En conclusión, la eficiencia de una computadora no reside solo en la fuerza bruta, sino en la inteligencia con la que se comunica con el mundo exterior.",
    ],
  },
  {
    id: 2,
    name: "Guion sobre Jerarquía de Memorias",
    contenido: [
      "En este video voy a explicar en detalle la jerarquía de memorias en un computador moderno y cómo esta organización es crítica para el rendimiento.",
      "Para analizarlo con datos reales, tomemos como referencia el procesador Intel Core i9-14900K, un chip donde la memoria no es un solo bloque, sino una pirámide compleja.",
      "El nivel más alto y rápido es la caché L1. Es extremadamente pequeña, apenas entre 64 y 80 KB por cada núcleo, pero su latencia es de solo 4 o 5 ciclos de reloj.",
      "Un escalón más abajo encontramos la caché L2, que en este i9 cuenta con 2 MB dedicados por cada núcleo de alto rendimiento, con una latencia de unos 12 a 15 ciclos.",
      "Luego llegamos a la caché L3, que es compartida por todos los núcleos y suma un total de 36 MB. Aquí la latencia ya sube a unos 10 o 15 nanosegundos.",
      "Finalmente, fuera del procesador, tenemos la memoria RAM DDR5 que puede llegar a 192 GB, pero cuya latencia es masiva en comparación: entre 60 y 100 nanosegundos.",
      "Para gestionar este abismo de velocidades, el procesador incluye un controlador de memoria integrado y utiliza una técnica llamada prefetching.",
      "El prefetching es esencialmente un sistema de predicción: el hardware intenta adivinar qué datos necesitarás a continuación y los trae de la RAM a la caché anticipadamente.",
      "Toda esta estructura se basa en el Principio de Localidad. Primero, la Localidad Temporal, que asume que si usaste un dato ahora, lo volverás a usar pronto.",
      "Segundo, la Localidad Espacial, que asume que si accedes a una dirección de memoria, probablemente necesites las contiguas, por lo que el sistema siempre trae bloques de 64 bytes.",
      "El diseño de esta pirámide implica trade-offs constantes. En los niveles cercanos al núcleo ganamos velocidad, pero pagamos con un alto consumo energético y generación de calor.",
      "En los niveles externos como la RAM, ganamos capacidad y menor costo, pero sacrificamos el tiempo de respuesta del sistema.",
      "En aplicaciones reales como servidores o máquinas virtuales, una caché L3 pequeña puede hacer que el bus colapse por el exceso de peticiones a la RAM.",
      "En conclusión, la jerarquía de memorias es un 'engaño' tecnológico necesario: le hace creer al procesador que tiene acceso instantáneo a gigabytes de datos.",
      "Sin esta organización estadística y física, incluso el procesador más potente del mundo se sentiría lento y torpe para el usuario final.",
    ],
  },
  {
    id: 3,
    name: "Guion sobre la ALU",
    contenido: [
      "En este video vamos a sumergirnos en el corazón matemático del procesador: la Unidad Aritmético Lógica, conocida universalmente como ALU.",
      "Si el CPU es el cerebro, la ALU es su calculadora interna, encargada de ejecutar cada suma, resta o comparación lógica que el software solicita.",
      "Para operar, la ALU utiliza registros internos denominados Registro A y Registro B, donde se cargan temporalmente los operandos antes del cálculo.",
      "La forma en que representamos los números aquí es vital. Para números enteros, utilizamos el sistema de complemento a dos, donde el bit de mayor peso indica el signo.",
      "Sin embargo, para cálculos científicos o gráficos, usamos números decimales bajo el estándar internacional IEEE 754 de coma flotante.",
      "Este estándar es fascinante porque divide un número de 32 bits en tres secciones: un bit de signo, un exponente para la escala y una mantisa para la precisión.",
      "La complejidad interna varía drásticamente según la operación. Una suma de enteros activa circuitos sencillos como el 'Full Adder' o sumador completo en un solo ciclo.",
      "Pero una multiplicación en coma flotante es como una orquesta coordinada: primero se calcula el signo con una puerta XOR, luego se suman los exponentes.",
      "Después, se multiplican las mantisas y, finalmente, se utiliza un circuito llamado 'shifter' para normalizar el resultado y ajustar el exponente final.",
      "Por ejemplo, al multiplicar 2.0 por 1.5, la ALU opera por separado la escala y la precisión para entregarnos exactamente 3.0 en formato binario.",
      "Esta complejidad técnica explica por qué las operaciones de coma flotante consumen más ciclos de reloj y mucho más calor que las operaciones enteras.",
      "Al finalizar cada cálculo, la ALU actualiza las banderas de estado o 'flags', informando si el resultado fue cero, si es un número negativo o si hubo un desbordamiento.",
      "Para un usuario, esto es invisible, pero en videojuegos o edición de video, la ALU realiza millones de estas operaciones en coma flotante por segundo.",
      "Si el diseño del multiplicador o del shifter es ineficiente, el rendimiento general del equipo caerá drásticamente, sin importar cuánta RAM tengamos.",
      "En conclusión, la ALU demuestra que la potencia real de un computador depende de la precisión con la que sus circuitos manipulan la electricidad para crear matemáticas.",
    ],
  },
  {
    id: 4,
    name: "Guion sobre Direccionamiento y Operandos",
    contenido: [
      "Bienvenidos. Hoy desglosaremos cómo el diseño de las instrucciones máquina define el flujo de datos dentro de un procesador, tomando como ejemplo práctico una operación de suma simple de 5 + 3.",
      "Cada instrucción debe indicarle al procesador qué operación realizar y, fundamentalmente, dónde encontrar los datos. Históricamente, esto ha evolucionado a través de tres esquemas clásicos que podemos comparar por su eficiencia.",
      "En primer lugar, tenemos la arquitectura de Pila. Esta utiliza un esquema de cero operandos explícitos, basándose en el principio LIFO, es decir, el último en entrar es el primero en salir.",
      "Como vemos en el esquema, para sumar, primero hacemos dos operaciones PUSH para apilar el 5 y el 3. La instrucción ADD no necesita parámetros, ya que automáticamente toma los dos valores superiores.",
      "Aunque las instrucciones son cortas, este modelo requiere 5 ciclos de reloj de la CPU, ya que depende de múltiples accesos a la memoria de la pila.",
      "En segundo lugar, observamos la arquitectura de Acumulador, que emplea un solo operando explícito. Este modelo clásico carga el primer valor en un registro central único y luego le suma el segundo.",
      "Es la opción menos eficiente en nuestro diagrama, requiriendo 3 accesos a memoria y 6 ciclos de CPU. Al centralizar todo en un solo registro, se genera un cuello de botella constante en el flujo de datos.",
      "En tercer y último lugar, llegamos a las máquinas de Registros, el estándar de la computación moderna. Aquí utilizamos 2 o 3 operandos, moviendo primero los datos desde la memoria RAM hacia compartimentos internos ultrarrápidos llamados registros, como R1, R2 y R3.",
      "Aunque el código resultante tiene más líneas de instrucciones, la ejecución es muchísimo más rápida: la suma se completa en apenas 3 ciclos de CPU, minimizando los accesos lentos a la memoria externa.",
      "Para que estos esquemas funcionen, necesitamos localizar la información utilizando modos de direccionamiento. El modo Inmediato es el más directo, ya que incrusta el valor constante directamente dentro de la instrucción.",
      "El direccionamiento Directo, por su parte, apunta a una ubicación de memoria específica y fija, mientras que el Indirecto es más dinámico, utilizando un registro como puntero hacia la dirección real en la RAM.",
      "También es fundamental mencionar el direccionamiento Indexado, que toma un valor base y le suma el contenido de un registro. Esto es vital para que los programadores puedan recorrer arreglos o tablas de datos mediante bucles de forma eficiente.",
      "Hoy en día, arquitecturas modernas como ARM priorizan un uso masivo de registros puros, ofreciendo hasta 32 registros de propósito general para mantener los datos cerca de la unidad aritmético-lógica.",
      "Mientras tanto, arquitecturas como x86 de Intel mantienen un esquema mixto para asegurar la compatibilidad con décadas de software heredado.",
      "Como conclusión, el diseño del conjunto de instrucciones es siempre un acto de equilibrio ingenieril: se busca minimizar los accesos a la memoria externa, incluso si eso significa aumentar ligeramente la cantidad de instrucciones que el procesador debe leer.",
    ],
  },
  {
    id: 5,
    name: "Guion sobre RISC vs CISC",
    contenido: [
      "Hablemos de las filosofías RISC y CISC, analizando cómo procesan un píxel en nuestro diagrama.",
      "La filosofía RISC (ARM Cortex-A72) apuesta por la simplicidad. Utiliza instrucciones atómicas que se ejecutan rapidísimo. Logra un IPC de 1 y usa muchos registros internos (R0 a R31) para evitar retrasos.",
      "Por otro lado, CISC (Intel Core i9) busca hacer más con menos código. Una sola instrucción puede cargar, procesar y guardar datos. Pero este hardware requiere dividir esa instrucción compleja en 'microoperaciones'.",
      "Esta complejidad pasa factura. Para procesar el píxel, RISC necesitó 3 instrucciones sencillas y 5 ciclos de CPU. CISC completó la tarea con 1 instrucción, pero requirió 10 ciclos por su pesada decodificación.",
      "La métrica más crítica es la energía. RISC consume apenas 5 vatios, dominando de forma absoluta el mercado de los teléfonos móviles.",
      "CISC, por su parte, dispara el consumo a 50 vatios por su enorme cantidad de transistores, siendo ideal para servidores donde sobra la energía.",
      "Hoy en día los procesadores modernos son un modelo híbrido: actúan como CISC por fuera para mantener compatibilidad con el software, pero internamente ejecutan microoperaciones veloces al estilo RISC.",
      "En resumen, la industria combinó la facilidad de programación de CISC con la velocidad atómica de RISC.",
    ],
  },
  {
    id: 6,
    name: "Guion sobre la Unidad de Control",
    contenido: [
      "Pasemos a la Unidad de Control, el 'director de orquesta' que genera las señales eléctricas para activar los componentes del procesador en el nanosegundo exacto.",
      "Cada instrucción se descompone en microoperaciones. Para gestionarlas, los ingenieros usan dos enfoques principales: Control Cableado y Control Microprogramado.",
      "El Control Cableado, típico de RISC, usa un circuito físico directo con puertas lógicas. Como vemos en la gráfica, es increíblemente rápido, ejecutando instrucciones en casi 1 ciclo de reloj. Pero es rígido: si hay un error, hay que rediseñar el chip.",
      "Para lograr flexibilidad, arquitecturas complejas como CISC usan el Control Microprogramado. Este diseño utiliza una memoria interna llamada 'Control Store'.",
      "En lugar de cables directos, la Unidad de Control busca en esta memoria un 'mini-programa' para saber los pasos a seguir. Esto requiere más ciclos por instrucción porque el procesador invierte tiempo leyendo su memoria interna.",
      "Sin embargo, su gran ventaja es que permite actualizaciones de firmware. Esto es vital hoy en día para la ciberseguridad.",
      "Si se descubre un fallo físico como la vulnerabilidad Spectre, no tiramos millones de computadoras. Se lanza un parche que reescribe el microcódigo, enseñándole a la Unidad de Control una secuencia segura.",
      "En conclusión, el diseño debe elegir entre la velocidad pura del hardware cableado y la versatilidad y seguridad del control microprogramado.",
    ],
  },
];
